version: "2"

linters:
  disable:
    - errcheck
  settings:
    govet:
      disable:
        - stdmethods

formatters:
  enable:
    - gofmt

issues:
  exclude-dirs-use-default: true
  exclude-dirs:
    - kitex_gen
  exclude-files:
    - ".*\\.mock\\.go$"

run:
  timeout: 5m
